name: Update NASA Pictures
on: 
  schedule:
    # 30min 4hr *everyDay *everyMonth *everyYear
    - cron:  '30 4 * * *'
  workflow_dispatch: {}
  
jobs:
  update-nasa:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Or another version

      - name: Install dependencies
        run: pip install requests lxml  # if you're using lxml; otherwise just requests

      - name: Update NASA feed
        run: python workflows/nasa-images.py

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add assets/feeds/nasa-images.xml assets/images/nasa-images/
          git diff --quiet && git diff --staged --quiet || git commit -m "Update NASA feed and images"
          git push
